[client]
# The URL of the minecraft server you wish to fetch mods from. This should be supplied by your server administrator
remoteServer = "https://localhost:8080/"
[security]
# The type of security that the remote server uses, for now supported are: publickey (default), password. If password is used, please set the server password below.
type="publickey"
# The server password: Change to the password you received from the server owner
password = "!!CHANGEME!!"
